log:
  level: debug
schema: xsd/NeTEx_publication-NoConstraint.xsd
input:
  - $HOME/.greenlight/documents
  - /etc/greenlight/documents
  - /documents
  - /greenlight/documents
  - ./documents
scripting:
  disableBuiltin: false
  paths:
    - $HOME/.greenlight/scripts
    - /etc/greenlight/scripts
    - /scripts
    - /greenlight/scripts
    - ./scripts
