input: testdata
output:
  log:
    level: debug
    disabled: false
    path: ~/.greenlight
  result:
    format: json # formats available are: json or xml
    disabled: false
validation:
  schema: xsd/NeTEx_publication.xsd # schema to use for validation, comes shipped with the source/container image
  builtin: true # whether to use builtin scripts
